#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

IF="${1}"
if [[ "x${IF}" == "x" ]]
then
    echo "Set interface"
    exit 1
fi

set -ex

echo "Setting up forwarding"
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv4.conf.all.send_redirects=0

echo "Setting up IPTables (v4)"
iptables -t nat -F
iptables -t nat -A PREROUTING -i "${IF}" -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i "${IF}" -p tcp --dport 443 -j REDIRECT --to-port 8080

echo "Setting up IPTables (v6)"
ip6tables -t nat -F
ip6tables -t nat -A PREROUTING -i "${IF}" -p tcp --dport 80 -j REDIRECT --to-port 8080
ip6tables -t nat -A PREROUTING -i "${IF}" -p tcp --dport 443 -j REDIRECT --to-port 8080

echo "Listing IPTables rules"
iptables -t nat -nvL
ip6tables -t nat -nvL

echo "Ready!"
